<MySwiper@MDSwiperItem>
    FitImage:
        source: 'images/DSC01244.JPG'
        radius: [20]

MDScreen:
    MDToolbar:
        id: toolbar
        title: 'Our Swiper App'
        pos_hint: {'top': 1}
        elevation: 10

    MDSwiper:
        size_hint_y: None
        height: root.height - toolbar.height - dp(40)
        y: root.height - self.height - toolbar.height - dp(20)

        MySwiper:

        MySwiper:

        MySwiper:

        MySwiper:

        MySwiper: