<Button>:
    font_size: 32
    size_hint: (.3, .3)

<MyWidget>:
    FloatLayout:
        size: root.width, root.height

        Button:
            pos_hint: {'x': 0, 'top': 1}
            text: 'Top Left'

        Button:
            pos_hint: {'x': .7, 'top': 1}
            text: 'Top Right'

        Button:
            text: 'Center'

        Button:
            text: 'Bottom Left'

        Button:
            text: 'Bottom Right'