<MyWidget>:
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        padding: 30

        Label:
            id: my_label
            text: 'Hello World'
            font_size: 32

        Button:
            id: my_button
            text: 'Press Me'
            font_size: 32
            size_hint: (.5, .5)
            pos_hint: {'center_x': .5}
            on_release: root.animate_it(self)