MDBoxLayout:
    orientation: 'vertical'

    MDScreen:
        MDRectangleFlatButton:
            text: 'Alert Popup'
            font_size: 24
            size_hint: .4, .2
            pos_hint: {'center_x': .5, 'center_y': .5}
            on_release: app.show_alert_dialog()

        MDLabel:
            id: my_label
            text: 'Some Stuff'
            font_size: 32
            pos_hint: {'center_x': .9, 'center_y': .2}