<MyWidget>:
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height

        Label:
            id: click_label
            text: 'Pick Favorite Pizza Below'
            font_size: 32

        Spinner:
            id: spinner_id
            size_hint: (None, None)
            size: root.width, 50
            text: 'Favorite Pizza'
            values: ['Pepperoni', 'Cheese', 'Mushroom']
            on_text: root.spinner_clicked(spinner_id.text)