<MyWidget>:
    do_default_tab: False
    size_hint: (.5, .5)
    pos_hint: {'center_x': .5, 'center_y': .5}

    TabbedPanelItem:
        text: 'Tab 1'
        Label:
            text: 'Hello World'

    TabbedPanelItem:
        text: 'Tab 2'
        BoxLayout:
            Label:
                text: 'Press button =>'
            Button:
                text: 'Press me'

    TabbedPanelItem:
        text: 'Tab 3'
        Image:
            source: 'Фото025.jpg'
