<MyWidget>:
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        padding: 30
        spacing: 15

        Label:
            id: slider_label
            text: 'Slide the Slider'
            font_size: 32

        Slider:
            min: 1
            max: 50
            step: 1
            orientation: 'horizontal'
            on_value: root.slider_it(*args)