<MyWidget>:
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        spacing: 20
        padding: 50

        Button:
            text: 'Hello World'

        Button:
            text: 'Goodbye World'

        Button:
            text: "I'm hungry"
            size_hint: (.5, .5)
            pos_hint: {'center_x': .5}
#            height: 50
#            width: 500