#:kivy 2.0.0
#: import utils kivy.utils

<MyWidget>:
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        padding: 10
        spacing: 10

        Button:
#            background_color: utils.get_color_from_hex('#a30b16')
            text: 'Hello World'

        Button:
#            background_color: utils.get_color_from_hex('#a30b16')
            text: 'Goodbye World'