MDBoxLayout:
    orientation: 'vertical'
    MDScreen:
        MDLabel:
            id: my_label
            text: 'Some Stuff'
            halign: 'center'

        MDFloatingActionButtonSpeedDial:
            data: app.data
            root_button_anim: True
            label_text_color: 1, 0, 0, 1
            bg_color_stack_button: 0, 1, 0, 1
            bg_color_root_button: 1, 0, 1, 1
            color_icon_root_button: 0, 1, 1, 1
            callback: app.callback